### ISSUE TITLE
Why do we print stuff on console with message?

### ISSUE THREAD

**Issue by berndbischl** [giuseppec/RBPcurve#6]
1) Info messages are OK. But is this info not always also displayed in plot? 
Are these message needed really or completely redundant?

2) If they are needed (in some cases):
a) use messagef from BBmisc, this is shorter
b) it is probably a good idea to be able to switch these messages off via an arg. I often call this "show.info"

**Comment by giuseppec** [comment]
Completely redundant messages have been removed. Show.info arg is added for some functions (where the message provides additional info and might help to understand the plot better).
